### ISSUE TITLE
Identification-free diaPASEF quantification

### ISSUE THREAD

**Issue by swillems** [Nesvilab/IonQuant#1]
Dear,

I was wondering if it was also possible to do quantification of diaPASEF fragments without prior identification?

Best regards,
Sander Willems

**Comment by swillems** [comment]
Dear,

I was wondering if it was also possible to do quantification of diaPASEF fragments without prior identification?

Best regards,
Sander Willems

**Comment by fcyu** [comment]
Hi Sander,

IonQuant is a label free quantification tool for timsTOF PASEF DDA.

Best,

Fengchao

**Comment by swillems** [comment]
Dear Fengchao,

I do realize this, but I was curious to see if there are any possibilities to extend this. In principle, if the quadrupole is ignored, precursor data from PASEF and fragment data from diaPASEF seems fairly similar to each other. For my own ion-networks tool (https://www.biorxiv.org/content/10.1101/726273v2), I rely on fully peak picked (rt, dt, mz, intensity) data, i.e. 4D features. For Waters data this is obtainable through proprietary software and the previous work of the Nesvizhskii group on IMTBX seemed promising as alternative. For timsTOF data I have not been able to find a software that performs such a peak picking / feature detection and I was under the impression that IonQuant could hopefully be a solution with a minimal amount of adaptations as the core mechanism already seems functional. I would be happy to try and collaborate on this, although my java skills are very rusty and my core expertise lies more in python.

Best regards,
Sander

**Comment by anesvi** [comment]
Dear Sander, 
We are debating how much effort to put into this. We will consider doing it if Bruker shows some support for our efforts. 
Alexey

**Comment by swillems** [comment]
Dear Alexey,

Thank you for the update. I understand such an effort needs to be worthwhile before you can commit to it. Keep me posted if something changes or if there is something I can do to help.

Best regards,
Sander
