### ISSUE TITLE
IonQuant never completes mixture model generation

### ISSUE THREAD

**Issue by jgriss** [Nesvilab/IonQuant#11]
Hi,

First of all, thanks a lot for the great tools!

I moved the FragPipe to a nextflow workflow and observed the IonQuant is repeatedly unable to fit a mixture model. What happens is that `Fitting a mixture model...` never returns and IonQuant seems to be stuck (without relevant CPU usage) for days. After that, I have to kill it without getting any error message that would allow me to determine what this is happening.

In the beginning, this only happened when I used ~10 PTMs in the MSFragger search. Now, I have one case where IonQuant worked as expected in the first run. But then, launching IonQuant with exactly the same input files, it's stuck again.

Example output:

```
2020-09-06 18:26:48 [INFO] - RT diff: -0.47714897893665453
2020-09-06 18:26:48 [INFO] - log10(intensity) diff: -0.6694718420067927
2020-09-06 18:26:48 [INFO] - correlation between runs: 0.02918378066132602
2020-09-06 18:26:48 [INFO] - matched run percentage: 0.09088300109135253
2020-09-06 18:26:48 [INFO] - Fitting a mixture model...
(never finishes)
```

Thanks a lot for the help!

Kind regards,
Johannes

**Comment by fcyu** [comment]
Hi Johannes,

Thanks for your interest in our tools. This issue is weird, and I don't think I can reproduce it with my own data. Could you please share your data with us? I can give you a link to upload if you want.

Thanks,

Fengchao

**Comment by jgriss** [comment]
Hi Fengchao,

I'd be happy to share the data privately with you. The total input data is 54G. Do you have some kind of storage where I can put it?

Kind regards,
Johannes

**Comment by fcyu** [comment]
Sounds great! Could you please upload your files to https://umich.app.box.com/f/37dcb43c67494da0844e41d3fb841dec ?

Thanks,

Fengchao

**Comment by jgriss** [comment]
Hi Fengchao,

I wanted to re-create all data for you just to be sure the error still persists. Naturally, now everything worked. I'll close this issue for now. Should it happen again I'll contact you.

Thanks for your time!

Kind regards,
Johannes
