### ISSUE TITLE
Questions about LFQ Match between runs

### ISSUE THREAD

**Issue by algom** [Nesvilab/IonQuant#13]
Dear Developers,

I'm testing Ionquant within Fragpipe (v14.0) and want to use match between runs. After reading the documentation and the preprint (Label-free quantification with FDR-controlled match-between-runs) still is not clear to me how it should set up when having many groups (with different RAW file number) in which I don't want to transfer the IDs between the groups, only within. In my setting I have two unfractionated samples (2-3 files each, technical replicates)  and some fractionated (6 fractions with technical replicates, ie 12, and other of 8 with tech replicates, i.e. 16 raw files), in which I want to compare the fractionation strategies to unfractionated samples:

Unfractionated A condition
RAW1a
RAW1b
RAW1c

Unfractionated B condition
RAW1a
RAW1b

Fractionated A condition
RAW1a
RAW1b
....
RAW12a
RAW12b

Fractionated B condition
RAW1a
RAW1b
...
RAW16a
RAW16b

From the documentation, I get (might be wrong) that the matching will be mainly controlled by the MBR Top runs and MBR min correlation. If want MBR between all files I should pick a number larger than all runs (here 16-17) and no min MBR correlation. In my case if I don't want to transfer between conditions, do I need to select a value of 2 (MBR top runs)? (it is the lower value of files, even 1 as in one condition I only have two files?). Thus, it will only pass within each group? if so, how would this affect the MBR in the fractionated samples with many files? Or would be a higher top runs but with a high min MBR correlation a better option?

The second question is about the MBR peptide FDR and MBR protein FDR, in the paper you use 0.01, is there a reason why the default is on 1, except for the MBR ion FDR which has 0.01? From the pre-pint I get that indeed is better to keep them all at 1%.

Thank you very much for the great software!

Regards,

Alejandro

**Comment by fcyu** [comment]
Hi Alejandro,

Thanks for your interest in IonQuant. Currently, we don't have a way to constrain the MBR in certain groups. As you found, IonQuant controls it using MBR top runs and MBR min correlation, which is like a automatic/adaptive constraint. We may add the hard constraint approach like what MaxQuant have in the next release.

Regarding the FDR, the default value is empirical and experimental according to our limited data and testing. You and other users may try and play with it and see what is the best value for you.

Best,

Fengchao
