### ISSUE TITLE
Generate MSStats.csv report from IonQuant without using FragPipe

### ISSUE THREAD

**Issue by avera1988** [Nesvilab/IonQuant#17]
Hello,

We are using IonQuant for peptide quantification after running a Linux command line pipeline as is described in: https://msfragger.nesvilab.org/tutorial_linux.html. We were able to produce all results from pepXML (MSFrager) to the quantification.csv (IonQuant) and all the *tsv reports from Philosopher and now we would like to generate a MSstats.csv table similar to the one that can be obtained by FragPipe but using the command line version of the software. Is there any flag or tutorial to do this directly on IonQuant without using the GUI FragPipe? I saw that the Philosopher report has the option --msstats . Is there a possibility to use this option with IonQuant to generate the MSstats.csv result table?

I hope you can help us.

Thank you in advance!

Arturo

**Comment by fcyu** [comment]
Yes, IonQuant will generate MSstats.csv file if you provide `--multidir` flag. You can find the detailed doc from https://github.com/Nesvilab/IonQuant. If you want some examples, you can let FragPipe to generate them by using "dry run" button. The only difference is that you don't need to provide those external libraries as what FragPipe is doing (you just need `java -Xmx64g -jar ionquant.jar .....`.

Best,

Fengchao

**Comment by avera1988** [comment]
Hi Fengchao,

Thank you very much for replying so fast. I will try to use the --mutidir flag. However, I have some questions on this I tried to look for the complete documentation of IonQuant in the link you sent and could not find any but the helpme of the program, is this multidir flag taking the results after run philosopher using the pipeline mode, something like this?

``
philosopher pipeline  --config params/philosopher.yaml control.dir treatment.dir
``
do we need to use abacus to aggregate data after multi experiment design?

Sorry for so many inquiries but we were unable to install FragPipe due to some admin issues in the HPC we have access to. Also, we would like to be able to run all the pipeline through a SLURM bash script, by submitting a job and without the necessity to log into a node and request a -X graphic environment.

Thank you!
Arturo.

**Comment by fcyu** [comment]
>  is this multidir flag taking the results after run philosopher using the pipeline mode, something like this?

I never used Philosopher's pipeline. I run Philosopher's commands separately as how FragPipe does. But the `--multidir` do need the tsv tables from Philosopher.


> do we need to use abacus to aggregate data after multi experiment design?

Yes, you need. You can see what command needs to be run using FragPipe's dry run.

Best,

Fengchao
