### ISSUE TITLE
How to annotate spectra to experiment and replicate?

### ISSUE THREAD

**Issue by comcon1** [Nesvilab/IonQuant#20]
Dear developers!

Thank you very much for your software. Could you please explain how to associate spectrum with experiment and replicate. Is it affects MBR procedure or I can simply annotate them in MSstats file after run.

Thank you.

**Comment by fcyu** [comment]
It won't affect MBR. But it affects peptide to protein rolling: there is only one intensity for a protein in a `exp_replicate` combination/folder.

Best,

Fengchao
