### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by IgorFesenko** [Nesvilab/IonQuant#21]
Dear developers,

Where can I find tutorials for LFQ analysis using MSfragger and IonQuant. The provided links do not work. Thank you!

Best regards,
Igor

**Comment by fcyu** [comment]
Hi Igor,

We moved our tutorials. You can find the tutorial about LFQ here (https://fragpipe.nesvilab.org/docs/tutorial_lfq.html). Other tutorials can also be find from https://fragpipe.nesvilab.org/.

Best,

Fengchao
