### ISSUE TITLE
MBR halting error

### ISSUE THREAD

**Issue by m-a-valach** [Nesvilab/IonQuant#23]
Having updated philosopher to v4.0.0, I also updated IonQuant to v1.7.5 as recommended — and all ran smoothly when not using the MBR option. However, when it is on (`mbr=1`), IonQuant comes to a halt once it has finished calculating the correlations between the runs: 
`2021-08-11 17:29:08 [INFO] - With ion FDR 0.010000, ion probability threshold is 0.981200`
`2021-08-11 17:29:08 [INFO] - With peptide FDR 1.000000, peptide probability threshold is -0.000100`
`2021-08-11 17:29:08 [INFO] - With protein FDR 1.000000, protein probability threshold is -0.000100`
`2021-08-11 17:29:08 [INFO] - Updating Philosopher's tables...`
`java.lang.NullPointerException`
`	at q.<init>(Unknown Source)`
`	at ionquant.IonQuant.main(Unknown Source)`
`2021-08-11 17:29:09 [ERROR] - null`

**Comment by m-a-valach** [comment]
Right, for decoys, `Prev AA` and `Next AA` in psm.tsv are empty. Printing of decoys in `Individual reports` is set to `true`. So, setting it to `false` should resolve the issue?

**Comment by fcyu** [comment]
Yes, setting it to false should be able to resolve this issue. Also, there is no need to print decoys for most cases because the PSMs already pass the FDR filtering.

Best,

Fengchao

**Comment by m-a-valach** [comment]
Thanks, Fengchao. The run completed without any hiccups after the suggested modification (in `Philosopher`'s pipeline configuration file).
