### ISSUE TITLE
does MBR ions part of the protein \ peptide summary table?

### ISSUE THREAD

**Issue by merbllab** [Nesvilab/IonQuant#24]
Hi,
I notice ionQuant issue a separate output file for MBR ions. are those ions also appear in the peptide / protein summary table? do I need to set a parameter other than the checkbox of MBR in the FragPipe ionQuant tab?
thanks
Assaf

**Comment by fcyu** [comment]
Hi Assaf,

The `mbr_ion.tsv` is a file containing all ions from MBR before FDR filtering. The ions passing FDR filtering will be in the ion.tsv, peptide.tsv, protein.tsv, combined_peptide.tsv and combined_protein.tsv.

For most cases, you don't need to change the parameter other than the checkbox of MBR.

Best,

Fengchao
