### ISSUE TITLE
There are only 4 negative data points in training. We need at least 10

### ISSUE THREAD

**Issue by stratei86** [Nesvilab/IonQuant#33]
Hi, I'm completely new to IonQuant but I believe my MBR is failing since I get missing values in the combined peptide report for peptides with no MSMS but clear MS1. I get this error message "There are only x negative data points in training. We need at least 10" for each sample, is that what is causing it? If so, is there anything I can do? I'd really appreciate if anybody could help

Thanks

**Comment by fcyu** [comment]
This error message is due to few peptides after the match-between-runs transferring, which indicates that your data does not have many high quality MS/MS or MS1. You may need to checking your parameters in MSFragger database searching, FDR estimation, and IonQuant. 

Best,

Fengchao

**Comment by stratei86** [comment]
Thanks a lot!!
