### ISSUE TITLE
Fractionated Silac Error in V19.0

### ISSUE THREAD

**Issue by Skourtis** [Nesvilab/IonQuant#35]
Hi, 

I just updated to v19.0 and I found I can no longer do an analysis I was doing on fragpipe v18.0. 

Basically I have a fractionated SILAC sample ( in the attached example 3 fractions, which all map to the same sample). 

V19.0 now immediately gives an error declaring that label quant doesn't support more than 1 run per experiment group (commit commit 962da7f10c2f31534805956fb2d42f0474a5eba4, Checking the experiment groups for label quant.) 

So is it possible to re-do the analysis I was doing with v18.0? where all 3 .mzML files were contributing to a single ion_quant.tsv files? My solution to this would be to run MSfragger on the 3 files with this manifest, and then once a combined pep.XML file is produced, then remove the two mzML entries from the manifest file, and run IonQuant, with now only 1 file per group.

Did I understand the issue correctly? Is it correct to do what I suggest with MSfragger?

Thank you,
Savvas

[lcms-files_2022-11-18_18-24-12.zip](https://github.com/Nesvilab/IonQuant/files/10180343/lcms-files_2022-11-18_18-24-12.zip)

**Comment by fcyu** [comment]
> So is it possible to re-do the analysis I was doing with v18.0? where all 3 .mzML files were contributing to a single ion_quant.tsv files? My solution to this would be to run MSfragger on the 3 files with this manifest, and then once a combined pep.XML file is produced, then remove the two mzML entries from the manifest file, and run IonQuant, with now only 1 file per group.

> Did I understand the issue correctly? Is it correct to do what I suggest with MSfragger?

No, you have to put your mzML files in separated groups. You can merge the ratios (by taking the mean or median) after FragPipe finishes but, unfortunately, I don't think your approach would work well.

Best,

Fengchao

**Comment by georgkus** [comment]
Hi Fengchao, 

Thank you very much for your quick response and for developing this brilliant software. I was discussing this issue with Savvas recently, as we would like to re-process previously published SILAC data on a fairly large scale. Do I understand correctly that IonQuant will work with "one-shot" SILAC samples, but not with fractionated SILAC samples? If so, are you considering to add that feature? I think that would be very helpful, since the vast majority of SILAC data currently come from fractionated samples (~80% of SILAC-based experiments in PRIDE include peptide fractionation).

Best,
Georg

**Comment by fcyu** [comment]
Hi Georg,

Thank you very much for your kind words.

> Do I understand correctly that IonQuant will work with "one-shot" SILAC samples, but not with fractionated SILAC samples?

Not exactly correct. IonQuant can surely analyze fractionated SILAC samples. Just need to put each fraction in an "experimental group". Then, all log-ratios (and other metrics) will be listed in columns of the `combined_*_label_quant.tsv` files. Then, you can process those values using your downstream tools. If you want to have a single log-ratio column from all fractions, you can take the mean or median of the original columns, which should not be very difficult.

> are you considering to add that feature? I think that would be very helpful, since the vast majority of SILAC data currently come from fractionated samples (~80% of SILAC-based experiments in PRIDE include peptide fractionation).

I might implement a module to "combine" multiple log-ratio columns into one as I described above. 

Best,

Fengchao

**Comment by georgkus** [comment]
Hi Fengchao,

Thanks a lot for your quick response. We will try the approach you suggest and I think it should work. 

In the future, I think it would be interesting to explore more complex strategies to combine SILAC ratios from different fractions. For example, if a peptide is present in low amounts in one fraction and high amounts in another, the latter SILAC ratios should be more accurate. At the protein-level, SILAC ratios resulting from multiple observations in one fraction would be more reliable that those from another fraction with a single observation. This type of information will be lost by simply taking the mean or median of SILAC ratios from different fractions. 

Best,
Georg

**Comment by anesvi** [comment]
Hi Georg

Just want to say thanks for the feedback, and when we get to work on it perhaps, we can reach out to you directly by email and you can help us test/benchmark the tools

Best,
Alexey

**Comment by georgkus** [comment]
Hi Alexey,

That would be great, thanks!

Best,
Georg
