### ISSUE TITLE
Can MSFragger perform protein grouping for multiple enzymatic digest?

### ISSUE THREAD

**Issue by TeckYewLow** [Nesvilab/IonQuant#41]
Hi,

I have a sample that was digested with 5 proteases. I am wondering if I can run these as a group and only produce one protein.tsv file that covers different digests? I want to improve coverage of proteins.

Thank you.

**Comment by fcyu** [comment]
It seems to be the same one as your previous question. I have transferred it to https://github.com/Nesvilab/FragPipe/issues/1052 since it is not only related to IonQuant but FragPipe. 
Best,

Fengchao

**Comment by TeckYewLow** [comment]
Thank you.That is a great idea!

Best regards,

Teck Yew
