### ISSUE TITLE
IonQuant from mzIdent files

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/IonQuant#45]
Dear IonQuant developers,

we recently came about the task to quantify old search results on the basis of precursor intensities. As the database search was quite exhaustive and took several weeks in total to complete, we thought about to re-quantify by using IonQuant. Is there any way to use mzIdent files instead of philosopher's psm.tsv files for such purposes in IonQuant (or maybe a parser to extract the neccessary columns and to generate a dummy psm.tsv file)?

Best regards,
Juergen

**Comment by fcyu** [comment]
> Is there any way to use mzIdent files instead of philosopher's psm.tsv files for such purposes in IonQuant (or maybe a parser to extract the neccessary columns and to generate a dummy psm.tsv file)?

We do not support the mzIdentML format, but feel free write a converter by yourself to convert it to the psm.tsv format.

Best,

Fengchao
