### ISSUE TITLE
MBR Crash

### ISSUE THREAD

**Issue by ChampionLab** [Nesvilab/IonQuant#46]
Hi IonQuant developers,

I'm having difficulty troubleshooting an odd error (short bit of log pasted below). Through a couple re-runs, I've observed that this is reproducible (occurs when processing the exact same file each time) only occurs if match between runs is checked/active. I've reproduced it on two computers, and even recopied the raw data from the instrument computer in case there was an odd corrupted file. I'm not sure why/what kind of error this is, if it is user error, bad file, or other. Could you help suggest next troubleshooting steps?

--Taylor Lundgren

2023-10-23 20:33:02 [INFO] - Training LDA models for all matched features.
2023-10-23 20:33:02 [INFO] - #{+1} = 39655, #{-1} = 10503, #{+2} = 12964, #{-2} = 3088
2023-10-23 20:33:02 [INFO] - Standardized coefficients:
2023-10-23 20:33:02 [INFO] - log10(intensity): 0.9073107266843821
2023-10-23 20:33:02 [INFO] - log10(KL): -0.0759261856876928
2023-10-23 20:33:02 [INFO] - abs(ppm): -0.23189203254296537
2023-10-23 20:33:02 [INFO] - IM diff: -0.2665987176855448
2023-10-23 20:33:02 [INFO] - RT diff: -0.2148805913569026
2023-10-23 20:33:02 [INFO] - Fitting a mixture model...
java.lang.IllegalStateException
	at umontreal.ssj.probdist.EmpiricalDist.cdf(EmpiricalDist.java:132)
	at a.a(Unknown Source)
	at t.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2023-10-23 20:33:03 [ERROR] - null
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

System OS: Windows 10, Architecture: AMD64
Java Info: 18.0.1.1, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
.NET Core Info: 6.0.23

Version info:
FragPipe version 20.0
MSFragger version 3.8
IonQuant version 1.9.8
Philosopher version 5.0.0

[log_2023-10-23_20-33-06.txt](https://github.com/Nesvilab/IonQuant/files/13110142/log_2023-10-23_20-33-06.txt)

**Comment by fcyu** [comment]
Hi Taylor,

Thank you very much for the bug reporting. I need your help to locate the bug. Could you download, replace the IonQuant in FragPipe, re run it, and send me the log file?

Here is the link to download https://www.dropbox.com/t/kwp0E6ECo6JmsKdw

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Taylor,

Thank you very much for the help. 

Now, I basically know what caused the crash. I could do a dirty fix by just skipping the data points with value `NaN` when fitting the model, but I would rather get to the bottom of the problem in case there are bugs hidden deeper. I can keep send you another version to print more info (and maybe more versions to run after that), or could you upload your files to https://www.dropbox.com/request/NvE1PQC8PR52ZGymPAjG so that I can reproduce and debug by myself? Let me know which one you prefer.

Thanks,

Fengchao

**Comment by fcyu** [comment]
500 GB! OK, here is another version to run: https://www.dropbox.com/t/Ob9pH2QmhwQF7EjC

Thanks again for your help.

Best,

Fengchao

**Comment by ChampionLab** [comment]
Next log is ready!
[log_2023-10-24_13-56-32.txt](https://github.com/Nesvilab/IonQuant/files/13125544/log_2023-10-24_13-56-32.txt)
Thanks,
Taylor

**Comment by fcyu** [comment]
Great! I think I am closing to get to the bottom of this issue. Here is another version to run: https://www.dropbox.com/t/UK5qT0hgM0oJcvYd

Thank you again for the help.

Best,

Fengchao

**Comment by ChampionLab** [comment]
[log_2023-10-24_17-40-08.txt](https://github.com/Nesvilab/IonQuant/files/13148735/log_2023-10-24_17-40-08.txt)
Last log for tonight. Thanks again,
Taylor

**Comment by fcyu** [comment]
Hi Taylor,

Thanks for the help. The log file seems to be the same as the previous one. I am not sure if I sent the wrong version. Let me change the version number and try again: https://www.dropbox.com/t/B1X48mAaIo3MFrds

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Taylor,

Thank you again for the kind help. I think I have figured out and fixed the bug. The pre-released version can be downloaded from https://www.dropbox.com/t/4Kx6VRox2jcfE5Gq . Let me know if there is any issue.

Best,

Fengchao

**Comment by ChampionLab** [comment]
Success! Thank you for the quick and effective responses.
