### ISSUE TITLE
SILAC channel intensity instead of only ratio

### ISSUE THREAD

**Issue by JonasAlbinus** [Nesvilab/IonQuant#48]
Dear Nesvilab,

Is it possible in the label_quant.tsv files to also get the Light, Medium and Heavy intensity instead of only the ratio? 

I'm asking because I am doing a 3 channel pulsed SILAC experiment and I am interested in the fraction of each SILAC channel, e.g. Light fraction = Light / (Light+Medium+Heavy). I'm currently using the "combined_modified _peptide.tsv" output to extract each SILAC modified version of my peptides and then sum it up to protein level from there. 

Kind regards, 
Jonas

**Comment by fcyu** [comment]
Hi Jonas,

Thanks for the feedback. Yes, we are working on adding this feature. Should be available in the next release if everything goes well. Stay tuned.

Best,

Fengchao

**Comment by JonasAlbinus** [comment]
Hi Fengchao, 

Thanks for the quick feedback. 
Awesome to hear that you are already working on adding this feature. I look forward to trying it out and hope the new release comes soon. 

Thanks, 
Jonas

**Comment by FriedLabJHU** [comment]
Any progress updates on this feature or how to turn it on if already incorporated?

**Comment by fcyu** [comment]
Hi @FriedLabJHU ,

Thanks for your interest in our tools. I was distracted by other projects recently. I will try to implement this month. Will let you know when it is ready.

Best,

Fengchao

**Comment by FriedLabJHU** [comment]
Thank you for building great tools! The last question is, will the SILAC protein intensities utilize the MaxLFQ normalization?

**Comment by FriedLabJHU** [comment]
My first instinct is to use the "convert" method because it would be directly traceable to ion intensities. However, I could appreciate a MaxLFQ-like normalization if the normalization factor functions being minimized only included log-ratios from the respective SILAC channels, but it could require calculating up to three minimizations per protein for L, M, and H channels.

How do you suppose the contributions from unlabelled ions be incorporated into either method?

Best,
Edgar

**Comment by fcyu** [comment]
Hi Edgar,

Thanks for the suggestions. I think it might be the best to generate both types of intensity: MaxLFQ and the one "converted" from the log-ratio. 

> How do you suppose the contributions from unlabelled ions be incorporated into either method?

They won't be used in the `label_quant` tables.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Edgar,

We have a pre-released version that will report both top-N and MaxLFQ intensities for MS1 label quant. If you want to have a try, could you send an email to yufeATumich.edu (replace `AT` with `@`)?

Thanks,

Fengchao

**Comment by fcyu** [comment]
The latest version has this feature implemented.

Thanks,

Fengchao
