### ISSUE TITLE
Estimation of RAM consumption by IonQuant

### ISSUE THREAD

**Issue by StephanEckert** [Nesvilab/IonQuant#51]
Dear Nesvilab,

we from the Kusterlab are currently trying to run a rather big LFQ search using FragPipe (V 21.1). It's comprised of 1261 samples (each measured for 2x 88 min with 10 compensation voltages in total, 2522 files in total) and 167 HeLa controls (each measured for 1x44 min with 1 compensation voltage, 167 files). In total 2689 files, ~1.7 TB.

Everything runs through smoothly until IonQuant starts. It always crashes after some time after finishing the “Collecting all compensation voltages if applicable...” step, after listing all CVs. The thrown error always is some form of out of memory error:” java.lang.OutOfMemoryError: Java heap space”.
![IonQuant Error](https://github.com/Nesvilab/IonQuant/assets/110918972/f3f81fb4-e47d-4e56-94b1-7977b5e0b77a)

We are running the search on a windows server having 512 GB of RAM. In the global settings tab, we set RAM to 0 and IonQuant was started with 440 GB of RAM. For IonQuant settings please see below.
![IonQuant Settings](https://github.com/Nesvilab/IonQuant/assets/110918972/3b976533-3975-498f-9319-483ba1bade56)

So, it seems like we need more memory. But before we start searching for a bigger machine, is there any chance this IonQuant run will ever finish? Is there a way to estimate upfront how much memory a run like this will need to finish?
Thanks in advance for your response!

Best,
Stephan

**Comment by fcyu** [comment]
Hi Stephan,

It seems that IonQuant required many RAM when loading the identification results. May I ask how you set the experiment groups?  Could you send the log file to yufe AT umich.edu?

Thanks,

Fengchao
