### ISSUE TITLE
Error when trying to download/update IonQuant [2.0] on Fragpipe

### ISSUE THREAD

**Issue by lxavierneves** [Nesvilab/IonQuant#53]
Hi, 

I've got an update notification on Fragpipe to download IonQuant [2.0] but when I click the download button the following error message is shown:

java.lang.Exception: Could not download IonQuant from the server.
	at com.dmtavt.fragpipe.tools.ionquant.IonQuantVersionFetcherServer.autoUpdate(IonQuantVersionFetcherServer.java:171)
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$actionIonQuantUpdate$12(TabConfig.java:506)
	at java.base/java.lang.Thread.run(Unknown Source)

is this a local issue? 
Anyway, I tried to download the new version directly from IonQuant GitHub but didn't find it. Any suggestions on how to get my fragpipe updated?

Many thanks,
Leandro

**Comment by fcyu** [comment]
I am not sure if I follow the question. There is no IonQuant version 2.0.

Best,

Fengchao

**Comment by lxavierneves** [comment]
ohh, I though there was because of the following notification displayed

![image](https://github.com/Nesvilab/IonQuant/assets/153612310/c4c11ef0-2269-4b15-9822-33ff14b8aa78)
