### ISSUE TITLE
Quantifying peptide modifications on top of fixed modifications (mass-offset search)

### ISSUE THREAD

**Issue by tjlundgren** [Nesvilab/IonQuant#55]
Hello Fengchao and others on the IonQuant team,

Using Fragpipe, I am searching for modified peptides with the labile/detailed mass-offset search and quantifying with IonQuant. I have one fixed modification, carbamidomethylation of cysteine (C 57.0215), and all other modifications defined with mass-offset. These are reported as a variable modification with the option to remove the mass offset from the delta mass.

I have some mass-offsets that apply to cysteine residues. In the PSM output, I see some examples of these modifications. For example, the 'Assigned Modifications' column will show 2C(57.0215),2C(mass offset, such as -57.0215 for a failed carbamidomethylation). 
However, I am unable to find any representation of this in the ion.tsv, or combined_modified_peptide.tsv. Perhaps this is user error, and I am looking in the wrong place/using wrong settings to quantify these peptides?

My main question: What is the best way to quantify variable modifications at positions of a fixed modification? (In my case, any modification of Cysteine). Can this currently be done with IonQuant? 

To check my understanding:
psm.tsv 'Intensity' is the IonQuant area under the curve for the feature. ion.tsv 'Intensity' is the sum of psms, and peptide.tsv the sum of ions.
combined_ion.tsv 'Sample_Replicate Intensity' column is the corresponding ion.tsv 'Intensity', normalized across samples.
combined_modified_peptide.tsv 'Sample_Replicate Intensity' is the sum of ions? then normalized across samples, or perhaps the sum of already normalized values from combined_ion? I'm not sure if there would be a difference.
I should be able to simply sum the reported psm intensities for mass-offsets on top of cysteines, but I do not know how to normalize across runs (which I think would be very beneficial). 

Thanks for your help and fantastic software!

**Comment by fcyu** [comment]
> I have some mass-offsets that apply to cysteine residues. In the PSM output, I see some examples of these modifications. For example, the 'Assigned Modifications' column will show 2C(57.0215),2C(mass offset, such as -57.0215 for a failed carbamidomethylation).
However, I am unable to find any representation of this in the ion.tsv, or combined_modified_peptide.tsv. Perhaps this is user error, and I am looking in the wrong place/using wrong settings to quantify these peptides?

Can you share your psm.tsv?

> My main question: What is the best way to quantify variable modifications at positions of a fixed modification? (In my case, any modification of Cysteine). Can this currently be done with IonQuant?

Yes, there is. I think what you did is correct.

Best,

Fengchao

**Comment by tjlundgren** [comment]
[A bit too big for github](https://drive.google.com/file/d/1isk7PVG4_3IXjEze1zq4lbRAzbKu7xb6/view?usp=sharing)

**Comment by fcyu** [comment]
Thanks for the file. I think I found out the reason. 

With closed search, Philosopher has a bug that when there are two modifications on the same site, the `assigned modification` column only shows the variable one. Thus, when IonQuant deals with this case, it assumes the existing of this bug and won't write both modifications in the other tables. 

For your mass-offset search, somehow there are two modifications on the same site in the `assigned modification` column. I am not sure what changed the Philosopher bug, but I will investigate it. For now, you could set the carbamidomethylation as variable modification, and adjust your mass-offset list to accommodate that. In this way, there won't be cases that one amino acid has two modifications.

Hope it helps,

Fengchao
