### ISSUE TITLE
IonQuant report it cannot find a sequence or ion or a peptide 

### ISSUE THREAD

**Issue by assafkacen1** [Nesvilab/IonQuant#56]
Hi
I get errors in the IonQuant log reporting it cannot find a sequence or an ion or a peptide, although they do exist in one of the input psm.tsv files. Can you elaborate on what the error means? 
I run IonQuant with just psm.tsv files and .raw files as input. It is not part of the FragPipe workflow 

Thanks

**Comment by fcyu** [comment]
Can you share the log file and psm.tsv file?

Thanks,

Fengchao

**Comment by assafkacen1** [comment]
if the files are too big through email, you can find them in the following link https://drive.google.com/drive/folders/1e8Dvua4pWRsg0v215NgXr2cBi-iWw2bY?usp=drive_link

**Comment by assafkacen1** [comment]
Hi Fengchao

Attached is the psm.tsv, ionquant log and masses. This is a collection of PSMs I would like to do MS1 quantification on them. I understand all the warnings in the log because I collected the PSMs from different searches. However, I do not understand the source of the errors. 

Thanks

**Comment by fcyu** [comment]
I just sent the request to get the access to your google drive folder.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @assafkacen1 ,

Thanks for sharing the files. I couldn't reproduce the error with your psm.tsv because the peptides could be found from my side. Maybe I can try again if you share your raw file, fasta, filelist_ionquant.txt, and the ionquant command with me.

Best,

Fengchao

**Comment by assafkacen1** [comment]
I added the raw file and the file list. Can it be something related to the IonQuant version? It is not the latest one. How does IonQuant know the fasta? I didn’t give it as an input

**Comment by fcyu** [comment]
> Can it be something related to the IonQuant version? It is not the latest one.

Yes, I think so because I couldn't reproduce the error using the latest version: [log.txt](https://github.com/user-attachments/files/16826323/log.txt)

> How does IonQuant know the fasta? I didn’t give it as an input

You are correct, IonQuant doesn't need fasta. I am not sure why I asked for that, maybe just some muscle memory 🫠

Best,

Fengchao
