### ISSUE TITLE
[ERROR] There are only 0 MS1 scans in (file directory / file name.mzML.

### ISSUE THREAD

**Issue by jmattin2** [Nesvilab/IonQuant#59]
I'm very new to fragpipe and proteomic analysis, I'm trying to analyze data I've downloaded from the PRIDE repository.  I downloaded it as a .mgf and used MSConvert to convert it to .mzML, and I'm getting the following error:

[ERROR] There are only 0 MS1 scans in (file directory / file name.mzML.
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping
Cancelling 1 remaining tasks

Because it's ending early I'm unable to get the combined_protein.tsv and other files I need, what is the root of the problem, how can I fix/troubleshoot it? Let me know if you need any additional information, please respond ASAP!

**Comment by jmattin2** [comment]
> There are no MS1 scans in your data. May I ask the settings when you perform the conversion?
> 
> Thanks,
> 
> Fengchao

![Screenshot 2024-11-18 132803](https://github.com/user-attachments/assets/90f753dc-8338-4681-b98d-ee88cdef5927)

**Comment by jmattin2** [comment]
Sorry, the files are `.mgf` , does that change anything? Or can I still follow the convert tutorial?

**Comment by fcyu** [comment]
> Sorry, the files are .mgf , does that change anything?

Yes, MGF format normally doesn't contain MS1 scans. It's basically useless if you want to perform the quantification.

Best,

Fengchao
