### ISSUE TITLE
Failure in MBR with timsTOF ddaPASEF data

### ISSUE THREAD

**Issue by ogtkk** [Nesvilab/IonQuant#6]
Hi,

When running MBR with timsTOF data, we frequently observe the following warnings and an error.
[WARNING] - Run SampleXXXX got nothing matched
[WARNING] - There is no mbr file for run XXXX. May be because it failed in MBR.

[ERROR] - There is no MBR result. Stop.

The error is data set dependent and some data sets can be correctly processed to the end.
Are there any possible causes and solutions? 
A log file attached.
[log_2020-06-26_18-48-44.txt](https://github.com/Nesvilab/IonQuant/files/4836659/log_2020-06-26_18-48-44.txt)

**Comment by fcyu** [comment]
Thanks for your interest in our tools. The log shows that the correlation of your runs are lower than 0.5, which is the threshold picking qualified runs to match. You can decrease `MBR min correlcation` to 0.

Best,

Fengchao

**Comment by ogtkk** [comment]
Thank you for your prompt reply. I tried MBR min correlation 0 but I got another error.
[ERROR] - Covariance matrix (column 8) is close to singular.

What correlation is it checking? Actually the data are duplicate analyses of same sample, and TIC looks like almost identical. I think it should be highly correlated.
[log_2020-06-26_23-57-49.txt](https://github.com/Nesvilab/IonQuant/files/4837687/log_2020-06-26_23-57-49.txt)

**Comment by fcyu** [comment]
It's the weighted retention time and ion mobility correlation between two runs. 

In terms of your new error, it's because there is not much ions can be match from one run to another. 

If appropriate, could you share your data with us? I can send you a link to upload.

Thanks,

Fengchao

**Comment by ogtkk** [comment]
Yes, I can share my data. Could you tell me the link?

**Comment by fcyu** [comment]
Thanks, here is the link: https://umich.app.box.com/f/f138483b17294b648ffff8e9d9fb232a

Best,

Fengchao

**Comment by ogtkk** [comment]
Thanks. I uploaded. Please check.

**Comment by fcyu** [comment]
Thanks for your information. We found a bug which is triggered when there are only two runs. We have pushed the fixed IonQuant (version 1.3.2) to the server. You should be able to get the notification next time starting FragPipe. Could you please try the new ionquant?

Thanks,

Fengchao

**Comment by ogtkk** [comment]
Thank you for fixing the bug so quickly. We tried some of the data which caused the error before and it was all successfully processed to the end. It's really excellent tool!

Thanks,

**Comment by fcyu** [comment]
Thanks for your positive feedback. Please feel free to contact us if there is any question in the future.

Best,

Fengchao
