### ISSUE TITLE
Label-based quantification parameters _ IonQuant

### ISSUE THREAD

**Issue by CFrey-palm** [Nesvilab/IonQuant#60]
Hello,

I have some questions about the use of IonQuant for label-based quantification (with SILAC or sequential isotopic labelling like in Desai 2022 article [10.1016/j.mcpro.2022.100218] samples). 

1. What does the "Re-quantify" parameter do ? Does it allow the specific search of a heavy (or light) ion from the identified light (or heavy) ion, and then the requantification the log2H/L ratio with the found intensity?
2.  Does any of the "advanced option" parameters have a control on the pairing of the light and heavy ions?
3. Why are the "Intensity" parameters on 0 by default (in SILAC3 for example) ?

Thank you and thanks for this great software!
Best.

**Comment by fcyu** [comment]
> What does the "Re-quantify" parameter do ? Does it allow the specific search of a heavy (or light) ion from the identified light (or heavy) ion, and then the requantification the log2H/L ratio with the found intensity?

Yes, your understand is correct.

> Does any of the "advanced option" parameters have a control on the pairing of the light and heavy ions?

What kind of "control" were you referring to?

> Why are the "Intensity" parameters on 0 by default (in SILAC3 for example) ?

0 means no limitation.

Best,

Fengchao

**Comment by fcyu** [comment]
> For example, will the heavy/light pairing be searched also within the "RT tolerance (min)"? 

Yes, the `RT tolerance (min)` controls that.

> Or are the entered numbers of min scans or min isotopes also required to search the complementary heavy ion based on a light ion?

Yes, the min scans and min isotopes are applied to all detected features, including from MS/MS identification, requantified, and MBR transferred ones.

Best,

Fengchao
