### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by Hyggern** [Nesvilab/IonQuant#7]
Dear Developers,

I hope this is the correct place for this report.

Despite setting the maximum Ram in the workflow under global settings during the IonQuant step on the 1.3.0 and 1.3.2 version it ends up maxing out the ram on the machine (28GB) and errors out.
<img width="908" alt="Screen Shot 2020-07-09 at 3 52 02 pm" src="https://user-images.githubusercontent.com/67984516/87002588-3cd99300-c1fd-11ea-962c-dbfb44de9ab8.png">
If there's anymore information or any logs that will help you along, please let me know. 

Kind Regards,

**Comment by fcyu** [comment]
Thanks for your interest in our tools. Since the "out of memory" error was thrown during data loading, I guess your data was larger than 28 GB or your machine actually didn't have 28 GB available at that time. We are sorry that there is not much we can do.

Best,

Fengchao
