### ISSUE TITLE
Silac quantitation

### ISSUE THREAD

**Issue by algom** [Nesvilab/IonQuant#8]
Dear IonQuant developers,

From the Readme file and old publications I read that MSFragger is capable of handling labeled samples (Silac, dimethyl) by adding variable modifications to the search parameters. As for IonQuant it reads "It supports match-between-runs (MBR) and light/heavy chemical labeling" and from the parameters help description and on Fragpipe I see the "label" parameter. Is this correct? If so I wonder how can use it? Does it mean to put the mass, for example in Silac, of light Lysine; mass of heavy Lysine? and then separate by a comma for Arginine? or is it a 0;8.01420,0;10.00827? 
I was able to run a test file without setting up the "label" option and get quantitations using the LFQ, but as far as I see it is summing up all modifications. I can only see the modifications with the intensities separated in the peptides.tsv.

Thanks for the great work.

**Comment by fcyu** [comment]
Thanks for your interest in our tools.

Yes, IonQuant supports labelling quantification. But both light and heavy labels must have non-zero masses, which means that SILAC is not supported. But dimethyl labelling is supported. What you need is putting the light and heavy mass to the `Label` field, for example `28.031300;34.063117`. 

Please note that the labelling support is still in its beta version. Feel free to let me know if there is any question.

Best,

Fengchao

**Comment by algom** [comment]
Dear Fengchao,

Thank you for the fast answer. I see, what a shame that SILAC is not supported, do you have any plans on supporting it in the future?

Alejandro

**Comment by fcyu** [comment]
Hi @algom ,

We are working on it now. Should be available soon. Will keep you posted.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @algom ,

We just release IonQuant-1.4.4 which contains SILAC support. You can either use the [FragPipe (GUI)](https://github.com/Nesvilab/FragPipe/releases/latest) or use the standalone command line tool ([https://github.com/Nesvilab/IonQuant/releases/latest](https://github.com/Nesvilab/IonQuant/releases/latest)).

Please feel free to let us know if there is any questions.

Best,

Fengchao
